upstream active_app {
    server green:3000;
}

server {
    listen 80;

    add_header X-Active-Slot "green" always;

    location / {
        proxy_pass http://active_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass http://active_app/health;
        access_log off;
    }
}
